services:
    rampmaster.onlinetime.listener:
        class: rampmaster\onlinetime\event\listener
        arguments:
            - @rampmaster.onlinetime.onlinetime
            - @dbal.conn
            - @path_helper
            - @template
            - @user
            - @request
        tags:
            - { name: event.listener }
    rampmaster.onlinetime.onlinetime:
        class: rampmaster\onlinetime\core\onlinetime
        arguments:
            - @rampmaster.onlinetime.formatter
            - @dbal.conn
            - @config
            - @template
            - @user
            - @auth
    rampmaster.onlinetime.formatter:
        class: rampmaster\onlinetime\core\formatter
        arguments:
            - @user
imports:
    - { resource: tables.yml }
